source "https://rubygems.org"

gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "minitest"
gem "dotenv"
#gem 'bcrypt'
# necessary to get bcrypt working on Windows:
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt', platforms: [:x64_mingw, :mingw]